### ISSUE TITLE
Handshake Failure: SSL Alert number 40

### ISSUE THREAD

**Issue by ParanoidUser** [gradle/wrapper-validation-action#69] opened 2022-11-09 00:18 UTC
Came across a sporadic SSL handshake failure in one of the parallel job executions. The same job passed from the second attempt after re-running. While it's unclear why higher TLS versions didn't work through in this case, it might be worth configuring OpenSSL to restrict SSLv3 usage on the client side.

<img width="674" alt="image" src="https://user-images.githubusercontent.com/5120290/200702536-61a8082f-9d4f-47d5-976a-f58450087f42.png">

Error: write EPROTO 140390028728256:error:14094410:SSL routines:ssl3_read_bytes:sslv3 alert handshake failure:../deps/openssl/openssl/ssl/record/rec_layer_s3.c:1546:SSL alert number 40

**Comment by TWiStErRob** [comment] 2022-11-29 21:39
I got exactly the same error, many times recently. This is because I added validation just recently to all my repos. I'm about to disable wrapper validation in some cases, because this happens too much in a huge matrix, and if one matrix job fails, I have to rerun the whole matrix. (This is a GitHub missing feature.) But the step shouldn't fail in the first place. All steps fire the requests at the same time on Gradle's server, depending on how in sync the runners pick up the job on GitHub Actions, could this be the problem? (DDoS)

`Error: write EPROTO 140558040758208:error:14094410:SSL routines:ssl3_read_bytes:sslv3 alert handshake failure:../deps/openssl/openssl/ssl/record/rec_layer_s3.c:1546:SSL alert number 40`

**Comment by ThadHouse** [comment] 2022-11-30 06:02
Doing some tracing, it seems like this is caused by ubuntu-latest switching over to ubuntu-22.04. My guess is something in OpenSSL is breaking this validation task.

**Comment by ParanoidUser** [comment] 2022-12-06 01:42
Hope it will be helpful to someone. As a workaround, I've switched to using [gradle-update/update-gradle-wrapper-action](https://github.com/gradle-update/update-gradle-wrapper-action) which verifies wrapper integrity upon updating ([docs](https://github.com/gradle-update/update-gradle-wrapper-action#security)).

__Pros:__ keeps Gradle wrapper up-to-date, what yet [not supported by Dependabot](https://github.com/dependabot/dependabot-core/issues/2223).
__Cons:__ [pushes unsigned commits](https://github.com/gradle-update/update-gradle-wrapper-action/issues/124) that may violate action permission policies in your repo.

**Comment by bigdaz** [comment] 2024-02-01 17:33
This looks like it should be fixed by #167

**Closed by bigdaz** 2024-02-01 17:33 UTC

**Comment by TWiStErRob** [comment] 2024-02-01 19:14
Nice, thanks @Marcono1234 and @JLLeitschuh for doing the heavy lifting!

It'll definitely decrease the probability of this happening significantly.

**Comment by bigdaz** [comment] 2024-02-01 22:12
@TWiStErRob You'll just need to wait for `v2.1.0` (or using the bleeding edge of `main` :) ).

**Comment by TWiStErRob** [comment] 2024-02-01 23:08
No worries, I got them stable by running once in a separate runner. Not the most cost-effective though.
